apiVersion: app/v1
kind: Deployment
metadata:
  name: api
  namespace: dev-voting
  labels:
    role: api
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec: 
    containers:
    - name: api
      image: cloudacademydevops/api:v3
      imagePullPolicy: Always
      env:
        - name: MONGO_CONN_STR
          value:  mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/langdb?replicaSet=rs0
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
      ports:
      - containerPort: 8080
      livenessProbe:
        httpGet:
          path:  /ok
          port: 8080
        iniitialDelaySeconds: 2
        periodSeconds: 5
      readinessProbe:
        httpGet: 
          path: /ok
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
        successThreshold: 1
    

