apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: dev-voting
  labels: 
    role: db
    env: dev
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: db